- name: Install core developer tools  (required to install some packages)
  yum:
      name="@Development tools"
      state=latest

- name: Install python and required packages
  yum:
      name={{ item }}
      state=latest
  with_items:
      - "{{ python_packages }}"

- name: Check for pip
  command: pip
  ignore_errors: true
  changed_when: false
  always_run: true
  register: check_pip
 
- name: Download pip
  get_url:
      url=https://bootstrap.pypa.io/get-pip.py
      dest=~
  when:
      check_pip.rc != 0
  
- name: Install pip
  command:
      python ~/get-pip.py
  when :
      check_pip.rc != 0
